### ISSUE TITLE
Introduction to Front-End tooling

### ISSUE THREAD

**Issue by fjaguero** [Valencia-JS/talks#1]
## Title of the talk

Introduction to Front-End tooling
## Format

Talk or Workshop.
## Talk level

Introductory
## Description

Introduction to modern web apps tooling. The objective is to empower developers to work in a faster and cleaner way.

Some topics that may be covered:
- Productivity
- Source Control
- Browser Development Tools
- Text Editors
- Automation (gulp)
- Code linting
- Terminal
  and more...
## Bio

Fernando is a Front-End developer at Mindrop, where he mainly writes Sass and JavaScript using the incredible Meteor framework. Outside the the office he is a member of Mozilla Hispano, helping to promote openness, innovation & opportunity on the Web. He also plays a lot of online games and usually is the best player on the losing team.

**Comment by danicatalan** [comment]
+1

**Comment by DavidBM** [comment]
+1 
Igual sería interesante que la chara se hiciera sobre gulp 4.0 que está a punto de salir. Cambia la forma de usarse y resuelve algunos problemas que tenia el 3 al basarse en orchestrator.

**Comment by fjaguero** [comment]
@DavidBM Perfecto, se podría mirar.

**Comment by MarioAraque** [comment]
Me gusta lo propuesto por @DavidBM.
No he asistido a la primera reunión, pero si la he visto por Youtube, y había mucha gente interesada en aprender y en mejorar las buenas prácticas (me incluyo). Lo que propone @fjaguero está muy bien, y también me gustaría proponer que se haga algo más práctico, por ejemplo que se haga la web de VlcJS usando todas las herramientas que se presenten (Yeoman, Coffeescript, Sass, etc), y se muestre cómo hacer un proyecto sencillo y usando buenas prácticas.

Encantado de poder ayudar en esta iniciativa, en lo que pueda.

Saludos.

**Comment by DavidBM** [comment]
Si quieres, @fjaguero, podemos quedar un día a las 7 y comentamos. Como cada uno está en una empresa distinta pueden salir cosas guays viendo como lo hace cada uno, problemas que hayan surgido, soluciones aplicadas, etc.

O lo comentamos por aquí. Aunque hablarlo en persona puede ser más agil.

**Comment by jonastg** [comment]
+1

**Comment by fjaguero** [comment]
@DavidBM Genial, podemos echarle un ojo la semana que viene y así lo preparamos para el evento. ¿Cómo lo ves?

**Comment by fjaguero** [comment]
@MarioAraque No está mal la idea, se podría hacer como side-project. Lo paso por la lista o directamente lo podemos comentar en la próxima reunión.

**Comment by DavidBM** [comment]
@fjaguero pues la semana que viene le damos un vistazo e intercambiamos ideas :)
