### ISSUE TITLE
The story behind es6katas.org - a different way of learning ES6

### ISSUE THREAD

**Issue by wolframkriesing** [Valencia-JS/talks#10]
Also only possible in July, if there is a meetup.

**Comment by fjaguero** [comment]
We need to confirm a date since it may be happening at the middle of July, not the beginning. Does that sounds good?

**Comment by wolframkriesing** [comment]
Hi
It depends on the exact date, don't worry about me. I won't be in vlc
before the 22nd I think
Wolfram
Am 28.06.2015 22:09 schrieb "Fernando Agüero" notifications@github.com:

**Comment by fjaguero** [comment]
Ok, we will talk about that tomorrow.
