### ISSUE TITLE
Talk proposal: ES6 introduction for Node.js

### ISSUE THREAD

**Issue by antoniobusrod** [Valencia-JS/talks#11]
Cause Node.js version 4 has been released last Tuesday, I would like to do a talk about how to use new ES6 features in a Node.js application as example!

**Comment by DavidBM** [comment]
Genial! Con tanto avance de versión, estaría bien tener un repaso de que es lo nuevo.

**Comment by rricamar** [comment]
Teniendo en cuenta que Node.js v4.0.0 va a ser LTS, ¡estaria perfecto!
Creo que nos interesa a todos :+1:

**Comment by alferpal** [comment]
La veo interesante. La verdad que también estaría bien mencionar con lo amplio que pueda ser ES6, qué parte está implementada según la versión de V8 estable ( activada por defecto), inestable ( detrás de flags), únicamente bajo strict etc Para gente que roza node de pasada puede ser interesante.

**Comment by fidelab** [comment]
A mi me parece que puede ser muy interesante no sólo para los que apenas
conozcan node si no también para los que trabajamos con él día a día.

2015-09-27 23:51 GMT+02:00 Alexandre Ferrando notifications@github.com:

> La veo interesante. La verdad que también estaría bien mencionar con lo
> amplio que pueda ser ES6, qué parte está implementada según la versión de
> V8 estable ( activada por defecto), inestable ( detrás de flags),
> únicamente bajo strict etc Para gente que roza node de pasada puede ser
> interesante.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Valencia-JS/talks/issues/11#issuecomment-143597250.

## 

Fidel Añó Bernat

**Comment by antoniobusrod** [comment]
Bueno, dado la inactividad, a no ser que ocurra lo contrario, en un par de días cerraré la propuesta de charla.

**Comment by fjaguero** [comment]
@antoniobusrod Desde luego es un tema interesante para todos

**Comment by DavidBM** [comment]
@antoniobusrod perdón, he estado inactivo un tiempo por problemas de trabajo.
Por mi parte organizamos la charla. Además tengo la idea de justo después de la charla hacer un taller de node y ES6 ligero. Así tenemos la jornada completa. :)

¿Qué te parece?

**Comment by antoniobusrod** [comment]
Hablamos mejor en privado, vía slack

**Comment by DavidBM** [comment]
Reabro esta issue. Cuando tengamos un evento confirmado con antelación te aviso @antoniobusrod  :)

**Comment by DavidBM** [comment]
El evento se hará el día 26, la idea es solo hacer charla y luego hacer el talle de @franciscop

**Comment by franciscop** [comment]
@toniconca y @pabbebo estáis invitados si queréis venir :smiley:

**Comment by DavidBM** [comment]
@antoniobusrod confírmame que este día 26 puedes hacer la charla y publico el evento :)

**Comment by antoniobusrod** [comment]
Ok. La charla tendrá una duración aproximada de 15-20min.

**Comment by franciscop** [comment]
@DavidBM ¿sobre qué hora será? ¿Preferís que la haga en inglés o en español (dependerá del público que asista normalmente)?

**Comment by ghost** [comment]
@franciscop por preferir que sea en castellano ;)

**Comment by DavidBM** [comment]
@franciscop Mejor en español. Para mucha gente es más ágil. Pues perfecto, voy a crear el meetup.

**Comment by antoniobusrod** [comment]
por cierto, sabéis que mucha gente estará en Madrid por el Codemotion en esas fechas, no?

**Comment by DavidBM** [comment]
Cierto @jordifreek, igual tendríamos que hacerla la semana que viene, el día 3. ¿Qué os parece @franciscop y @antoniobusrod ?

**Comment by antoniobusrod** [comment]
OK por mi parte.

**Comment by DavidBM** [comment]
@antoniobusrod Dame una pequeña descripción de la charla y una pequeña bio tuya. :)
Por aquí o por slack.

**Comment by antoniobusrod** [comment]
Te lo envío a través de slack

**Comment by franciscop** [comment]
Yo el día 2 y 3 justo no puedo, podría ser el 4?

**Comment by DavidBM** [comment]
Un viernes es complicado, mucha gente desaparece el fin de semana. El día 1 que tal te va? @franciscop

**Comment by DavidBM** [comment]
@franciscop te va bien el día 1?

**Comment by franciscop** [comment]
Sí, perfecto. Esta tarde os envío la bio

**Comment by antoniobusrod** [comment]
El día 1 no puedo por la tarde. Supongo que yo también estoy involucrado
ese día.

On Fri, 20 Nov 2015 12:34 Francisco Presencia notifications@github.com
wrote:

> Sí, perfecto. Esta tarde os envío la bio
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Valencia-JS/talks/issues/11#issuecomment-158369153.
> 
> ## 

Antonio Bustos R.

**Comment by DavidBM** [comment]
Ok, pues pasemos a la siguiente si se puede. Que tal os va el día 8, 9, y 10? Con que alguno podáis los dos lo hacemos. @antoniobusrod @franciscop

**Comment by antoniobusrod** [comment]
8 y 10

**Comment by franciscop** [comment]
Los 3 me vienen bien, aunque por [Digitall](http://vitemprende.es/es/animacion-el-director-de-atrapa-la-bandera-y-las-aventuras-de-tadeo-jones-y-el-estudio-creador-de-los-minions-estaran-en-digitall/) y la disponibilidad de @antoniobusrod diria que el 8 de Diciembre es el mejor dia. Por otro lado el 8 es festivo y el 9 no, asi que mucha gente habra vuelto ya del puente

**Comment by antoniobusrod** [comment]
Francisco tiene razón, no creo que sea buena idea hacer la meetup en un festivo. No había caído con ello. Creo que el mejor dia seria el jueves 10.

**Comment by DavidBM** [comment]
Entonces el jueves día 10 de diciembre? 
@franciscop tú puedes el día 10? 
Si me dices que sí le doy pistoletazo de salida a todo esto.

**Comment by antoniobusrod** [comment]
@DavidBM hay novedades respecto a la charla??

**Comment by DavidBM** [comment]
Sí, perdón.

Parece ser que las naves ya tiene reservado el día 10. Con lo que nos proponen que lo hagamos el día 20, pero claro, son las elecciones, así que le he dicho si pueden el 18 o 17. ¿Vosotros podéis uno de esos dos días?

Está siendo complicado cuadrar fechas, pero lo conseguiremos. 

@franciscop @antoniobusrod

**Comment by llunaplanet** [comment]
Buenas gente, el último Meetup de Valencia Hardware
http://www.meetup.com/es/ValenciaHardware/events/226713549/ lo hicimos en
coSfera , un espacio de Coworking nuevo, no creo que tengan problema de
fechas.

Preguntarles en hola@cosfera.es

Saludos!

Enviado con MailTrack
https://mailtrack.io/install?source=signature&lang=es&referral=llunaplanet@gmail.com&idSignature=23

Enviado con MailTrack
https://mailtrack.io/install?source=signature&lang=es&referral=llunaplanet@gmail.com&idSignature=23

**Comment by antoniobusrod** [comment]
@DavidBM por mi parte solo jueves 17

**Comment by franciscop** [comment]
Yo tengo un examen importante el 21 así que la semana anterior no podré. Propongo mantenerlo el 10 en la UPV o en Cosfera. En Cosfera nos tendríamos que asegurar que la gente se puede sentar, ya que por lo que ví era un sitio sólo para dar charlas y para el workshop nos interesaría que la gente pueda apoyar el portatil.

Si no, el 22 y 23 me vienen bien también.

**Comment by DavidBM** [comment]
Hola gente, como habréis podido ver no he estado muy presente últimamente. Esto se debe a un virus intestinal que se me ha complicado y a problemas laborales que he tenido durante estos meses.

Visto lo visto, **aplazamos el evento**. Esto no quiere decir que no lo vayamos a hacer, pero no será en diciembre. A veces las fechas son complicadas!

Quería aprovechar el evento para decir que dejaba de ser el organizador de ValenciaJS (me voy a Alemania a trabajar) y que si alguien tiene la ilusión y le gusta la comunidad tiene la oportunidad de darle su toque personal organizándola. Por su puesto tendría asistencia de mi parte como yo la tuve de @fjaguero. Como el evento ha sido imposible, lo digo ahora y en el próximo correo lo mencionaré.

Ha sido un tiempo muy agradable con vosotros. Hay gente muy buena y con mucho talento, tanto técnico como humano. Llevar ValenciaJS ha sido de las experiencias más enriquecedoras de mi vida.

Pues eso, tenéis más tiempo para preparaos las charlas :P

**Comment by antoniobusrod** [comment]
@DavidBM te acabo de contestar por privado en https://valenciajs.slack.com/

**Comment by franciscop** [comment]
Buenas, no pasa nada, yo pasé uno así hace un par de semanas y fué un infierno. Os parece bien si @antoniobusrod y yo lo hablamos y buscamos una fecha? Creo que sería mucho más fácil de organizar de esta forma (he organizado varias charlas/eventos previamente). Por lo que veo sería por Enero.

Sobre llevar el grupo, estuve pensando en hacer uno de Node.js a parte o dentro de este, pero yo también me voy a principios de Febrero fuera de España así que decidí no hacerlo por el poco tiempo y veo difícil poder ayudar con este en el futuro.

**Comment by DavidBM** [comment]
He creado este hilo para hablar sobre el tema: https://github.com/Valencia-JS/valenciajs.org/issues/6

**Comment by antoniobusrod** [comment]
@franciscop OK a organizar la charla entre los dos. Yo también estoy interesado en atraer interés hacia Node.js en Valencia, y creo que ValenciaJS es un buen lugar para ello!

**Comment by DavidBM** [comment]
Os puedo pasar contactos de lugares y cuando tengáis fecha lo publico en Meetup. De todas formas, en la medida que me sea posible os ayudo en lo que haga falta.
