### ISSUE TITLE
The offline web + PouchDB

### ISSUE THREAD

**Issue by daleharvey** [Valencia-JS/talks#12]
I maintain an open source project called PouchDB and would be happy to do a talk about what the offline web is, why developers should care and what they can use to build offline capable web applications.

**Comment by daleharvey** [comment]
Oh and I forgot to mention, this would have to be in english, lo siento but I recently moved to Valencia and my Spanish definitely isn't good enough to do a talk in it yet :)

**Comment by DavidBM** [comment]
I think that is a very interesting talk :)
It can be useful for many people.

**Comment by fjaguero** [comment]
+1 to this as it's a hot topic now. Offline-first is something that many people didn't even heard about.

**Comment by DavidBM** [comment]
What do you think will be the duration of the talk?
We can make the talk near 26 of November, what do you think?

Maybe you can make a talk + little workshop or demonstration :)

**Comment by DavidBM** [comment]
@daleharvey ?

**Comment by jonastg** [comment]
Hi @daleharvey! Are you still interested in doing the talk?
