### ISSUE TITLE
Workshop de drive-db

### ISSUE THREAD

**Issue by franciscop** [Valencia-JS/talks#13]
# Propuesta

Un **workshop para usar un spreadsheet de google drive como base de datos** gracias a **[drive-db](https://github.com/franciscop/drive-db)**, una herramienta que hice hace un año y usa selectores similares a MongoDB. Ejemplo:

``` js
// Include the module and tell it which spreadsheet to use
var drive = require("drive-db")("1BfDC-ryuqahvAVKFpu21KytkBWsFDSV4clNex4F1AXc");

// Load the spreadsheet
drive.load(function(err, db){

  // Find all Johns by their last name
  var Johns = db.find({ firstname: "John" }).order('lastname');
});
```
## El workshop
- **Introducción** 5': explico qué es drive-db y cómo funciona por encima, aunque como referencia está [la documentación](https://github.com/franciscop/drive-db/blob/master/documentation.md)
- **Primer ejemplo** 10': creamos todos un excel y el proyecto de node para trabajar, una sencilla view de jade con una tabla y un each. Lo ejecutamos y vemos como se llena la tabla con los datos que hemos metido en el excel.
- **Segundo ejemplo** 15': mostrar una gráfica a través de los datos del excel, que puede ser con [chart.js](http://www.chartjs.org/) o con [Chartist.js](http://gionkunz.github.io/chartist-js/). Los modificamos para ver cómo va cambiando.
- **Tercer ejemplo** 15': tiempo libre para que cada uno desarrolle lo que quiera, arreglar problemas previos o descansar.
- **Despedida** 5': posibilidades y limitaciones de drive-db y otros sistemas similares.
## Requisitos

Los participantes tienen que saber javascript y preferiblemente haber tocado algo de node.js. Tienen que tener una cuenta de heroku, de google drive y de github. También tienen que tener node y npm instalados para facilitar las cosas. Necesitaremos internet donde se haga el workshop.
## ¿Por qué hice `drive-db`?

Hace un año hice una pequeña herramienta para poder mostrar los eventos que íbamos a hacer en [Makers UPV](http://makersupv.com/) en una web. Decidimos almacenarlos en un Spreadsheet de Google Drive para facilitar que varios miembros de la asociación pudieran editarlo sin problema ya que ninguno es informático y el sistema que teníamos de wordpress era demasiado complejo para nuestras necesidades. Poco a poco fue creciendo y ahora es la web actual, junto con drive-db y se han ido adaptando hasta llegar a lo que son ahora.
## Conclusión

¿Qué os parece el workshop? ¿Sería interesante para alguna charla de ValenciaJS? Tendría que ser en Noviembre (excepto durante la [Be Maker Faire](http://www.bemaker.org/) del 13-14 Nov) o la primera quincena de Enero. Puedo darla en español o en inglés sin ningún problema (he leido por ahí que había alguno que no hablaba español).

**Comment by DavidBM** [comment]
Me parece muy interesante. A ver si para la semana que viene empezamos a organizar nuestro primer evento :)

¿Para cuando te vendría bien hacerla?

**Comment by fjaguero** [comment]
Pinta muy bien!

**Comment by franciscop** [comment]
La semana del 16 de Noviembre o la siguiente, Cualquier día por la tarde o el finde me vienen bien

**Comment by franciscop** [comment]
¿El domingo 22 por la tarde, por ejemplo? ¿Dónde son las charlas y workshops?

**Comment by DavidBM** [comment]
Voy a ver si lo podemos hacer en el local Yo Maker. Les envío un correo. ¿Cómo te va el día 26?

**Comment by llunaplanet** [comment]
Buenas, David, creo que Yo Maker cerró hace poco

Que hay de GeeksHubs? Y no se pueden seguir haciendo en Las naves?

Saludos

**Comment by franciscop** [comment]
Yo Maker no los conozco lo cual es muy ironico pero tambien off topic...

En Geekshub di una charla en febrero con frontenders, puedo preguntar a ver si nos dejan pero tendria que ser en otro sitio porque la sala en la que la di era de charlas y programar ahi lo veo dificil. El local de Las Naves también me parece perfecto, pero ya no tengo casi contacto con ellos asi que seria mejor que contactarais vosotros si conoceis.

O lo podemos hacer en la UPV ya que puedo reservar salas sin problema, estan preparadas para esto y puede acceder todo el mundo entre semana.

¿Qué preferís?

**Comment by DavidBM** [comment]
Puedo hablar con las Naves, ya me dijeron que se ofrecen a ello :)
Intento llevar cierta rotación en los sitios a los que vamos para no ser dependientes de un local.
La anterior charla fue en Geekshubs, así que ahora tocaría en las Naves / UPV. A la upv no hemos ido nunca. 

Yo hablaría con las naves y si no se puede con la UPV.

**Comment by DavidBM** [comment]
Te parece bien el día 26 en las Naves? @franciscop

**Comment by franciscop** [comment]
Si es a cualquier hora a partir de las 4 de la tarde me viene perfecto :+1:

**Comment by DavidBM** [comment]
@franciscop Dame un pequeño bio sobre ti :)

**Comment by jonastg** [comment]
@franciscop sigues interesado en realizar el workshop?

**Comment by franciscop** [comment]
No, me fui de España hace unas semanas y antes me fue imposible, lo siento por no avisar...

**Comment by jonastg** [comment]
Lástima... suerte por ahí fuera! :)
