### ISSUE TITLE
Taller de ES6

### ISSUE THREAD

**Issue by marcelkalveram** [Valencia-JS/talks#14]
He visto la propuesta de @antoniobusrod y se me ocurrío hacer un pequeño taller sobre ES6 porque ultimamente he leído mucho sobre el tema y es algo que me gustaría profundizar con una charla.

Sería para diciembre porque este mes voy un poco liado todavía.

**Comment by fjaguero** [comment]
Totalmente +1!

**Comment by DavidBM** [comment]
Genial! Pues ya tenemos un taller para diciembre :)
@antoniobusrod hace la charla de introducción para Node 4 (que es la que trae ES2015). Igual le interesa participar en el taller

**Comment by antoniobusrod** [comment]
No se cómo quieres enfocar el taller, pero podría echar una mano. Si quieres, comentame vía https://valenciajs.slack.com/

**Comment by jonastg** [comment]
Hola Marcel!

Sigues interesado en realizar el taller sobre ES6??

**Comment by marcelkalveram** [comment]
Hola @jonastg, en principio si. Lo que pasa es que antes de mayo no creo que pueda hacerlo. ¿Te parece una opción o es demasiado tarde?

**Comment by marcelkalveram** [comment]
Hola de nuevo, han pasado algunos meses, pero todavía estoy interesado en hacer una charla/un taller sobre ES6. Habrá evento en febrero? @DavidBM @antoniobusrod @jonastg ¡Gracias!

**Comment by jonastg** [comment]
Hola @marcelkalveram! Para hablar de ES6, creo que un taller sería más idoneo que una charla, pero lo dejamos a tu elección. De momento no tenemos nada cerrado para febrero. ¿Qué disponibilidad tienes tu para hacer una charla/taller?

**Comment by antoniobusrod** [comment]
Hola! @marcelkalveram qué duración tendrías prevista para la charla/taller? La última vez que hicimos algo parecido en [abril 2016](https://www.meetup.com/ValenciaJS/events/230322517/), se nos quedó un poco corta la sesión, por lo que lo ideal hubiera sido haber hecho ese taller un sábado por la mañan para disponer de mas tiempo. Mi intención es en un futuro (próximo), retomar talleres para hacer los cursos de NodeSchool :)

**Comment by jonastg** [comment]
Claro, la vez que hicimos el taller se nos quedó corto de tiempo. La cuestión sería buscar el sitio que nos permita estar más tiempo para hacer un taller de 2 o 2,5 horas.

**Comment by marcelkalveram** [comment]
Creo que preferiría una charla en a mitad/finales de Febrero. No sé si tengo tiempo para preparar un taller de 2-3 horas, pero si luego vemos que mucha gente interesada en un taller lo podemos hacer en Marzo y me daría más tiempo para prepararlo. ¿Cómo lo veis?

**Comment by antoniobusrod** [comment]
Hola @marcelkalveram , hace tiempo hicimos una charla sobre el mismo tema, pero aun así, te animo a preparar primero la charla y si conseguimos suficiente gente interesada en continuar con un taller, también lo podemos mirar.

**Comment by marcelkalveram** [comment]
OK, si ya se ha hecho una charla sobre ES6, podría hacer sólo el taller en Marzo. También puedo pensar en otro tema para la charla. Últimamente he trabajado mucho con React Native. No sé si es algo que os interesa también?

**Comment by antoniobusrod** [comment]
Tampoco te preocupes, la charla se hizo hace un año https://www.meetup.com/ValenciaJS/events/228786386/ por lo que siempre viene bien recordar mas funcionalidad que está soportada o si quieres introducir conceptos de ES7. Sobre React Native, estamos encantados de organizar charlas de cualquier tema relacionado con JS :D

**Comment by jonastg** [comment]
Hola @marcelkalveram! Qué tal? Has pensado finalmente en algo? Como fechas disponibles estarían el jueves 2 o el jueves 9 de marzo, sino ya estaríamos hablando de una fecha para después de fallas

**Comment by marcelkalveram** [comment]
Hmm, bueno. Entonces creo que me gustaría enfocarlo un poco más en React Native que ES6. Y puedo hablar un poco de mi experiencia desarrollando una app para iOS y Android. 

Tengo un discurso que preparar para principios de marzo, pero si queréis hacemos éste después de fallas, el 23 de marzo. ¿Que os parece?

**Comment by jonastg** [comment]
Perfecto entonces! :) Cuando puedas pasarnos un título + descripción + bio, lo publicamos en el meetup. Tienes el mail de Toni o mio?

**Comment by marcelkalveram** [comment]
Vale, intentaré pasartelo todo hasta finales del mes.

**Comment by marcelkalveram** [comment]
@jonastg ok, ya la tengo. Pásame tu email y te lo envío todo. ¡Gracias!

**Comment by antoniobusrod** [comment]
Hola @marcelkalveram , si estás en https://vlctechhub.slack.com/messages, nos encontrarás :) Sino, sería una perfecta oportunidad también :)
