### ISSUE TITLE
Taller MEAN Stack (ng2) + IoT + Azure

### ISSUE THREAD

**Issue by javierdelacueva** [Valencia-JS/talks#17]
Título:
Taller MEAN Stack (ng2) + IoT + Azure

Formato: 
Workshop

Nivel de la charla: 
Introductoria (creo)

Descripción: 
La idea sería hacer un workshop en el que mostrar como usar MEAN Stack con Angular 2 y los componentes IoT de Azure para crear una aplicación que lea información en tiempo real de un dispositivo IoT (Raspberry + sensor) y muestre la muestre en un panel de control. Creo que sería un taller bastante interesante y que puede dar ideas de como utilizar javascript no solo para aplicaciones Cloud.

Si la charla interesa, prepararé muchas cosas con antelación y dejaré la parte divertida para el workshop así los asistentes podrán ver como conectar el dispositivo a la nube, como almacenar la información y mostrarla en tiempo real.

Bio de ponente: 
Javier de la Cueva, trabajo en el equipo de arquitectura IoT en everis y mi tiempo libre lo uso para estar siempre al día en todo lo relacionado a JS.

**Comment by cristobal-io** [comment]
Suena interesante, aunque voy muy liado, a esta me apunto. 

Tal vez antes del workshop estaría bien poner algunos enlaces con referencias a las herramientas para poder traer la lección de casa algo estudiada.

**Comment by jonastg** [comment]
A mi también me parece interesante.

@javierdelacueva ¿cuánto tiempo crees que necesitarías? y en función del tiempo necesario ¿prefieres que sea una tarde entre semana o aprovechar la mañana de un sábado?

**Comment by javierdelacueva** [comment]
Yo creo que mejor una tarde entre semana. Puedo dejarlo todo ya montado y solo centrarme en las partes más interesantes:

- Código en Raspberry que conecta con IoT Azure
- Código en NodeJS que recibe de IoT Azure y envía a frontEnd
- Código en Angular2 que recibe los datos y pinta la gráfica

Puedo mostrar los dos ejemplos de tiempo real con socket.io y llamada REST a base de datos.

Un Saludo.

**Comment by antoniobusrod** [comment]
Entonces sería mas una charla-taller-práctico que un workshop? Me refiero para organizar el evento en un lugar o en otro lugar, por si quieres que sea asistido o que cada uno vaya intentandolo a la marcha

**Comment by javierdelacueva** [comment]
OK, sí, sería un charla-taller. Para hacerlo tipo workshop quizá el contenido sea demasiado largo. Si te parece lo que podemos hacer es lo orientamos a una charla y si a la gente le gusta, ya preparo workshops más específicos sobre IoT y javascript: como usar el Azure IoT Hub, Angular2 en tiempo real, etc...

**Comment by franciscop** [comment]
¡Estamos organizando uno prácticamente igual en la UPV! ¿Cuándo tienes pensado hacerlo @javierdelacueva? El que estamos organizando es igual pero con este stack:

- Arduino u Raspberry Pi
- Node.js y Heroku
- Websockets y seguramente jQuery y Chart.js

¿Entiendo que lo vais a hacer en la Cueva? El que tenemos en marcha nosotros es mucho más sencillo y nos centraremos en la parte de Node.js, Heroku y los gráficos, dejando la parte de Arduino un poco de lado ya que es con [Makers UPV](https://makersupv.com/) y de eso los que vienen suelen controlar.

**Comment by antoniobusrod** [comment]
Hola @javierdelacueva , qué te parece si organizamos tu charla para después de vacaciones Semana Santa - Pascua y dejamos el taller para un futuro?

Si prefieres, podemos concretar la fecha de manera más cómoda para en Slack [escribiendome a @antoniobusrod](https://vlctechhub.slack.com/messages/@antoniobusrod) o a [ @jonastg  ](https://vlctechhub.slack.com/team/jonastg)

**Comment by antoniobusrod** [comment]
ping @javierdelacueva

**Comment by javierdelacueva** [comment]
Hola Antonio,
Disculpa la demora. Vamos a hablarlo por Slack para concretar fechas pero creo necesito que me des acceso al equipo para que podamos hablar.

También me puedes escribir a jdelacue(at)everis.com y lo hablamos por ahí.

Un Saludo.

**Comment by antoniobusrod** [comment]
Hola @javierdelacueva , te acabo de mandar una invitación usando https://valencia-devs.herokuapp.com/

**Comment by jonastg** [comment]
Hola @javierdelacueva, te escribimos hace un par de días por slack, retomamos el tema de la charla?

**Comment by Jorgegarve** [comment]
Hola @jonastg, disculpa que no estaba atento a slack. Ahora me vuelvo a conectar y retomamos la conversación. Gracias.

**Comment by antoniobusrod** [comment]
Hola, como ya hicimos la charla el año pasado, voy cerrando la _issue_
