### ISSUE TITLE
Workshop Node.js

### ISSUE THREAD

**Issue by franciscop** [Valencia-JS/talks#18]
Propongo hacer un taller de Node.js introductorio para hacer una pequeña web, ya sea un chat con websockets o algo tipo twitter (muro y likes),  excluyendo el paso de auth en ambos. Me haría falta saber dos cosas para poder prepararlo:

1. El público: ¿programadores en otros lenguajes probando Node.js o gente que está empezando?
2. ¿Cuántos? Para mi, idealmente 4-12 para hacerlo interactivo suponiendo que me pueden ayudar 1-3 personas.
2. El lugar: ¿disponéis de algún lugar que podamos usar o tenemos que encontrar uno?

El tiempo de taller sería 1.5-2h e idealmente acabarían cada uno con un deploy en Heroku de su aplicación. Tendrían que traer Node.js, NPM y Git ya instalados.

**Comment by antoniobusrod** [comment]
Hola @franciscop , la idea nos parece muy buena!

> El público: ¿programadores en otros lenguajes probando Node.js o gente que está empezando?

Al ser la comunidad ValenciaJS, puedes esperar que los asistentes tengan los conocimientos básicos en cuanto al lenguaje, por lo que no te preocupes por el nivel.

> ¿Cuántos? Para mi, idealmente 4-12 para hacerlo interactivo suponiendo que me pueden ayudar 1-3 personas.

Sería una pena limitar a un número tan pequeño el taller, por lo que lo ideal sería encontrar un espacio para unas 20-30 personas como mínimo.

> El lugar: ¿disponéis de algún lugar que podamos usar o tenemos que encontrar uno?

Podemos encargarnos de hablar con diferentes espacios para encontrar el lugar perfecto.

**Comment by franciscop** [comment]
Ya tenemos montado y organizado un taller de Node.js & IoT con @makers-upv la semana que viene, qué fechas crees que serían buenas para el que estoy proponiendo aquí, @antoniobusrod ? Segunda semana de Mayo?

**Comment by antoniobusrod** [comment]
@franciscop cuál es tu disponibilidad para la segunda-tercera semana de mayo? Prefieres un tarde de lunes-jueves o sábado por la mañana?
