### ISSUE TITLE
Hacking de videojuegos con JavaScript

### ISSUE THREAD

**Issue by karliky** [Valencia-JS/talks#19]
**Hacking de videojuegos con JavaScript**

**Formato:** Charla de 50 minutos
**Nivel de la charla:** Avanzada

**Descripción:** 
¿Cómo hacen trampas los hackers en los videojuegos? ¿Se puede hackear World Of WarCraft con JavaScript?. En esta charla veremos cómo explorar videojuegos utilizando sólo JavaScript/Node.js. Repasaremos diferentes juegos como OverWatch o Guild Wars 2 y explicaré cómo tomar el control de un videojuego incluso llegando a las profundidades de su código ensamblador.

Algunos ejemplos de lo que podríamos ver en la charla:
https://www.youtube.com/watch?v=r8BAlc5fS0g
https://www.youtube.com/watch?v=8N7ck29ymek

**Bio de ponente:** 
Soy Carlos Hernández Gómez - https://twitter.com/k4rliky - y en mi tiempo libre me dedico a estudiar cómo funcionan los motores JavaScript (V8, SpiderMonkey, etc), soy full stack developer y trabajo en Audiense, donde hacemos analíticas para redes sociales.

PD: Ya sé que las charlas deben ser de 30 min, pero en mi caso, por lo especial de la charla, la puedo dar de 45 min mínimo y de ahí estirarlo hasta una hora si queréis. Propongo de 50 min simplemente por tener un término medio.

**Comment by jonastg** [comment]
Hola Carlos! 

Me gusta la idea! :) ¿Qué disponibilidad tienes para hacer la charla?

En cuanto al tiempo no hay problema, como si la duración es de hora y media, normalmente el meetup trata un único tema/charla. Saludos

**Comment by karliky** [comment]
Hola @jonastg !

Yo trabajo en remoto en Madrid pero tengo familia en Valencia, así que puedo trabajar desde allí, simplemente decidme una fecha y yo veo si me cuadra con todo y me paso allí unos días en Valencia. No necesito alojamiento ni transporte ni nada, solo un proyector que funcione :P.

Un saludo!

**Comment by jonastg** [comment]
Hola @karliky, por la fecha no hay problema que sea un día un otro, somos flexibles :D ¿qué tal te vendría el jueves 22 u otro día de esa semana?

**Comment by karliky** [comment]
Hola @jonastg

Entiendo que estamos hablando del 22 de Junio, me parece bien. Si me confirmas esa fecha por mi parte todo ok! ¿A que hora sería? Y ¿en qué lugar?.

**Comment by jonastg** [comment]
@karliky pues sería el 22 de junio si y la hora a la que suele comenzar el meetup es las 19h. En cuanto al sitio, tenemos que cerrar la localización. Te escribo por privado.

**Comment by karliky** [comment]
estupendo!

**Comment by jonastg** [comment]
Hecha, gran charla!
