### ISSUE TITLE
Workshop proposal

### ISSUE THREAD

**Issue by markpiller** [Valencia-JS/talks#20]
Hey guys, I will be visiting Valencia on March 11th and would love to conduct a workshop for your group. The subject of the workshop is "Developing scalable serverless apps". The level is intermediate, however, both beginners and advanced developers will be able to learn new things. During the workshop, we will explore how to build apps without spending any time on server-side tasks. Any JS developer will be able to build highly scalable apps without any need for a server-side team. We will explore how to interact with the cloud database, handle user registration, login, explore development of a chat app and look into Cloud Code.

I run a software product company called Backendless. We provide a cloud-based platform which powers thousands of apps. The apps which run with Backendless can be native mobile, however, many developers use our platform to develop hybrid applications, or apps built with ReactNative, Ionic. Most importantly, you can build applications without worrying and spending any time on the backend - just focus on the UX and app logic.

**Comment by antoniobusrod** [comment]
Hi @markpiller , we are finding a spot for the talk, we will come back to you. Consider your proposal accepted.

**Comment by antoniobusrod** [comment]
Accepted and scheduled!
