### ISSUE TITLE
Feature Flags en Frontendlandia con Google Optimize

### ISSUE THREAD

**Issue by raulmoyareyes** [Valencia-JS/talks#21]
Desplegar a producción nuestros proyectos es un paso que nos genera un estrés añadido en nuestro día a día. ¿Y si es viernes? Como no quieres recibir llamadas de cólera para apagar fuegos mientras disfrutas de tu finde, evitas desplegar. Cuando nuestros peores miedos ocurren ¿cómo arreglamos rápidamente el bug? ¿Volvemos a la versión anterior? La solución: usar Feature Flags.

Hablaremos sobre qué son, cómo los utilizamos y cómo nos salvan los fines de semana.

**Comment by raulmoyareyes** [comment]
Hola! Os propongo una charla para septiembre, en torno al 26 puede ser una opción genial. ¿Cuál es el siguiente paso?

![](https://media.giphy.com/media/3rgXBQIDHkFNniTNRu/source.gif)

Muchas gracias.

**Comment by jonastg** [comment]
Gracias por la propuesta! Te escribo por privado para los detalles.

**Comment by antoniobusrod** [comment]
Event approved and scheduled!
https://www.meetup.com/ValenciaJS/events/264612456/
