### ISSUE TITLE
Decentraland primer contacto: JS, 3D, p2p y blockchain en el navegador

### ISSUE THREAD

**Issue by pabloes** [Valencia-JS/talks#29]
Decentraland, primer contacto: JS, 3D, gamedev, p2p y blockchain en el navegador

## Nivel
Principiante

## Duración
Sobre 45 minutos (por definir)

## Condicionantes
Jueves 12 de Diciembre, oficinas de Flowable / flowable
Flowable/Mimacom, Avda Cortes Valencianas 58, 7º, 5

## Descripción
Hablaremos del proyecto “decentraland” y la tecnología que lo envuelve.
Empezaremos poniendo en contexto revisando teconologías entorno al navegador: webworkers, comunicación p2p (webRTC), IPFS, webGL/webGPU, interacción con Ethereum.
Veremos qué es decentraland, el estado actual del proyecto y cómo desarrollar en la plataforma.
Acabaremos examinando algunos ejemplos de código incluyendo un smart contract en lenguaje Solidity.

## Acerca del ponente
Pablo estornut, twitter: @pablo_es
Más de 10 años de experiencia en empresas de IT, marketing y diseño. Últimos 7 años como “Frontend” en Flowable
Cuarto puesto en el último hackaton de decentraland (GameJam 2019)

**Comment by antoniobusrod** [comment]
Hola @pabloes , me gustaría preguntar si estas en la comunidad [vlctechhub](https://vlctechhub.slack.com/) de Slack. En ese caso, escribenos (`@jonastg` and `@antoniobusrod`) para concretar la fecha del evento por privado.

**Comment by pabloes** [comment]
Hola @antoniobusrod , no estoy en la comunidad, slack me dice:
"Ponte en contacto con el administrador de tu espacio de trabajo y pide una invitación"

**Comment by jonastg** [comment]
Pues registrarte desde [aquí](https://slack.vlctechhub.org/), introduces mail y obtienes la invitación para entrar.
