### ISSUE TITLE
React.js: Primeros pasos 

### ISSUE THREAD

**Issue by skozz** [Valencia-JS/talks#3]
![Reactjs](http://cl.ly/image/391T242s2M2h/logo-reactjs.png)

**Título de la charla**
React.js: Primeros pasos

**Formato:**
Charla

**Nivel de la charla:**
Introductoria
**Importante:** toda la charla está en ES6 (ECMAScript6)

**Descripción:** 
Conoceremos los conceptos básicos de React, como trabajar con one-way-binding y el funcionamiento de su DOM virtual entre otras cosas. 

La idea es salir de la charla con los primeros pasos necesarios para hacer una aplicación en pocos minutos. 
- Introducción a React: qué es y porqué emerge
- Sintaxis JSX
- Componentes y la comunicación entre ellos
- _State_ y _Props_ 
- Lifecycle
- ~~_Mixins_ y cómo evitar código redundante~~ lo comentaremos pero no profundizaré ya que los mixins en ES6 ya no están soportados. 
- Ejemplos prácticos de React 

Nota: es posible que la lista anterior se quede corta con respecto a la charla, pretendo explicar más cosas con demos y eso dependerá del tiempo que tengamos. 

**Bio de ponente:** 
Aunque inicialmente fui forjado con Ruby y Python ahora disfruto desarrollando aplicaciones JavaScript. En la actualidad mi trabajo diario me permite desarrollar en profundidad React en producción y conocer más de cerca las virtudes y desgracias de esta librería.

**Comment by fjaguero** [comment]
Genial, la ponemos para Junio como me habías dicho.

**Comment by DavidBM** [comment]
Me gusta! Tengo ganas de ver como funciona React!

**Comment by danicatalan** [comment]
Mola!

**Comment by rlucha** [comment]
+1

**Comment by jonastg** [comment]
+1

**Comment by skozz** [comment]
Comentaros que una mala coincidencia me ha llevado a comentar con @fjaguero de aplazar mi charla al siguiente ValnciaJS, las muelas del juicio han llamado a mi puerta y me han dado cita para el 29 de este mes, por lo que es poco probable que para el día 2 esté totalmente recuperado.

**Comment by skozz** [comment]
Se me olvidaba: de todas formas publicaré alguna demo y parte del contenido de la charla desde mi blog estas semanas previas así que cuando estén os pego un toque para abrir boca desde aquí.

**Comment by skozz** [comment]
He actualizado la ficha de la charla, a falta de que @fjaguero confirme todo el próximo ValenciaJS tendremos React.
