### ISSUE TITLE
Things I wish someone told me about NodeJS or How Node can shoot you in the foot

### ISSUE THREAD

**Issue by alferpal** [Valencia-JS/talks#4]
<h1>Título de la charla

<h5>Things I wish someone told me about NodeJS
Or how Node can shoot you in the foot

<h1>Formato:

Charla, aunque algunos de los puntos prácticamente dan para una charla por si solos.

<h1>Nivel de la charla:

Puede hacerse totalmente introductoria o más avanzada dependiendo de qué problemas / soluciones que los asistentes quieran que se comenten ( ver propuestas en la descripción ).

<h1>Descripción:

Como se ha indicado arriba, la charla puede hacerse más o menos extensa, de mayor o menor amplitud o dificultad en función de la profundidad a la que se quiera llegar en los siguientes puntos:
- Librería estándar de Node
- Módulos
- NPM y paquetes útiles
- Pequeñas cosas de Node
- Callback Hell
- Don't block your Event Loop
  - Soluciones, sus problemas y las soluciones a los problemas de las soluciones.
- La pregunta del millón: NodeJS o io.js
- Preguntas, cuestiones, flamewars.

Por otro lado también se podría hacer alguna serie de charlas con esto, quizás ¿?

<h1>Bio de ponente:

Estudiante de ingeniería Informática, 24 años, desarrollador backend por ahora sin proyecto, antes en ehumanlife. Ha utilizado C, C++, Java, programado alguna que otra cosa para Android y al final ha acabado en NodeJS donde tiene, si puede, pensado exprimir todo lo que pueda del ecosistema.

Bueno, ya comentáis que os parece

**Comment by fjaguero** [comment]
Los puntos a los que les daría un +1 son: "Módulos", "Pequeñas cosas de Node" y "Don't block your Event Loop".

Si alguien hace otra charla más introductoría, esta podría ser más avanzada. He añadido un campo en el perfil de Meetup para que cada uno pueda poner qué tipo de charla busca y así tener una métrica lo que esperan la gente apuntada.

Por otro lado, si quieres dejar un bloque para profundizar en otro ValenciaJS, ¡genial!

**Comment by alferpal** [comment]
Realmente lo de dejar bloques para profundizar pasa como en cualquier punto de otras charlas. Por ejemplo, cada herramienta de tu charla daba para otra charla según lo quieras enfocar.

Como tengo más o menos ideas y ejemplos de código para cualquier sección de las que he comentado, voy a esperar un poco a ver que es lo que más se pide y según eso la enfoco y el resto se guarda para otras :+1:

**Comment by DavidBM** [comment]
Yo veo más interesantes estos puntos:
- Módulos
- Pequeñas cosas de Node
- Callback Hell (Aunque esto es más de JavaScript que de node, npm tiene muchas librerías últiles para solucionarlo)
- Don't block your Event Loop
- NodeJS o io.js

Por sugerir algo, diría que se haga desde el punto de vista de que sabemos como va un servidor y lo que nos aporta node. Donde sirve y donde es un tiro en el pie usarlo.

Yo tenia intención de hacer una de browserify, con lo que tu charla puede ser una introducción a la mía. Si quieres lo comentamos más a fondo :)

**Comment by llunaplanet** [comment]
La pregunta del millón yo creo que para las cervezas de después no? ;)

**Comment by dreamersp** [comment]
Hola!

No sé cómo abordaréis el Callback-Hell, pero si no es con Promesas, quizá sea mejor replanteárselo.

En mi equipo (WonderBits) nos hemos hecho amantes de las promesas, en su encarnación de Bluebird, más rápida y limpia que Q.
En AngularJS antes de la v.2 viene Q integrada, error que corregirán en la 2.0, pero claro, la rotura de compatibilidad va a ser tremenda por el resto del API.

Da gusto ver gente tan activa en la comunidad :)
Saludos!

**Comment by alferpal** [comment]
Básicamente esa era la idea de lo que tenía pensado hablar en Callback Hell. Describirlo, ver como es habitual que se te vaya de las manos, y hablar de promesas.

**Comment by fjaguero** [comment]
Justamente hoy me he estado peleando con Q en un Express. Genial entonces lo que vas comentar @alferpal.

**Comment by Bloodsucker** [comment]
A mi me molaría ver algo sobre debugging, que aunque por internet hay cosas... siempre ha sido horrible debuggear nodejs.

**Comment by alferpal** [comment]
Por ir limpiando un poco las issues, dejo las slides por aquí y cierro esto.

http://www.slideshare.net/AlexandreFerrandoPal/things-i-wish-someone-told-me-about-node-js
