### ISSUE TITLE
Learn METEOR in less than 30 minutes (Talk + Small Workshop)

### ISSUE THREAD

**Issue by Bloodsucker** [Valencia-JS/talks#5]
# Learn Meteor in less than 30 minutes

Talk, and after it an interactive demo.
## Talk level

Introductory - intermediary
## Description

Come and meet the most modern and AWESOME platform to date, Meteor, and learn how to build a real-time multi-client web application in minutes. Meteor has been described by their authors as

> Build apps that are a delight to use, faster than you ever thought possible.
> 
> Meteor is a complete open source platform for building web and mobile apps in pure JavaScript.

After trying the platform by myself, I have to say that this is certainly true. Follow me and I will show you why they are right and why you will love the platform right after the talk.

During the talk, we will see an initial overview of the Meteor platform and its main components.

After it, you will discover how easy is to develop a demo app and interact with it. @donflopez will show you how to do it. 

**Feel free to bring your laptop.**
## Some topics that may be covered:
1. What is Meteor
2. Database. Everywhere.
3. Blaze & templating
4. Publications and subscriptions
5. Securing our application
6. Latency Compensation
7. Let’s embrace the platform
## Shall I know something before coming?

Actually... not so many things. If you know to code a little bit and know the basics of JavaScript then you are ready. If you are worried because you are a back-end web developer, remember that Meteor is a full-stack platform.

MongoDB knowledge is not required, however it would be easier for you to better understand some stuff.
## Who am I

José Cabo, Javascript Engineer at Mindrop. You can learn more about me in [my LinkedIn profile](https://es.linkedin.com/in/josecabo) profile and follow me in [@JoseCaboCarsi](https://twitter.com/JoseCaboCarsi)

**Comment by fjaguero** [comment]
En este caso sería una charla y un pequeño workshop, por lo que pueden traer su portátil y trabajar la demo que se desarrollará. Seguro que está interesante ver otro mindset diferente :+1:

**Comment by DavidBM** [comment]
Yo me apunto sin dudarlo :)

**Comment by Ryckes** [comment]
+1
¿Tiene fecha ya?

**Comment by fjaguero** [comment]
@Ryckes La idea es hacerlo el próxim martes 5 de mayo. En cuanto confirmen creo el evento. Si estás en el grupo de Meetup te llegará un email.

**Comment by danicatalan** [comment]
De cabeza!

**Comment by josesegarra** [comment]
Al apuntarme me ha llegado "lista de espera". Esta completo el aforo ?

**Comment by fjaguero** [comment]
@jsegarra1971 Sí, esta completo según lo esperado. De todos modos, estate atento a
durante el día de hoy ya que mandaré un correo electrónico para que los que no van a ir, dejen su entrada. Nunca va el 100% de la gente que está apuntada.

**Comment by josesegarra** [comment]
Ya tengo sitio. Gracias y nos vemos manyana.
