### ISSUE TITLE
Backbone essentials. Tips & good practices

### ISSUE THREAD

**Issue by basiclines** [Valencia-JS/talks#6]
Estaría genial que alguien que se haya pegado mucho con Backbone se animará a dar una charla sobre esto.
Yo he hecho unos primeros pasos siguiendo algunos tutoriales, pero creo que es interesante hablar sobre ello, si alguien con experiencia se anima claro!

**Comment by Bloodsucker** [comment]
Creo conozco a la persona ideal. @Gywem, anímate y hazla!

**Comment by DavidBM** [comment]
¿Sigue habiendo alguien interesado en esta charla?

**Comment by pabloesm** [comment]
Yo estaría encantando de que alguien la hiciese... Pero también entiendo que si no hay un poco más de interés general, no merece mucho la pena el esfuerzo de currarse una charla.

**Comment by basiclines** [comment]
Yo estaba bastante interesado, pero ahora estoy en Madrid por tiempo indefinido, por tanto me es un poco dificil atender a los meetups!

**Comment by jonastg** [comment]
@Gywem estarías interesado en realizar la charla??
