### ISSUE TITLE
Arquitectura, los años perdidos

### ISSUE THREAD

**Issue by llunaplanet** [Valencia-JS/talks#7]
Hola! Me gustaría proponer una especie de mesa redonda / debate en torno a cómo organizamos el código de nuestros proyectos, siendo aplicable tanto al frontend como al backend.

Una vez una aplicación empieza a tener cierta envergadura, por ejemplo usando MVC, empieza a ser un poco engorroso moverse por los diferentes archivos / carpetas con cierta agilidad, ( sobre todo cuando hay MVC tanto en frontend como en backend)  en nuestro caso, en este punto nos empezamos a plantear si hay formas más eficientes de estructurar el código.

Así llegué a este gist en GitHub ( que no tiene desperdicio ), en el cual muchos developers exponen sus preferencias personales a la hora de estructurar el código, hay para todos los gustos:

https://gist.github.com/lancejpollard/1398757

Me han parecido súper interesantes varias referencias a un método de "agrupación por funcionalidad o intencionalidad", enlazan con una charla de Robert Martin, en ella Robert incide en el que lenguaje de programación / framework no debe dominar la estructura principal de tus directorios y simplemente expone teorías de arquitectura formuladas en los años 70, de ahí el título de su charla, “Arquitectura, los años perdidos"

https://www.youtube.com/watch?v=WpkDN78P884

¿ Que os parece ?  
¿Os parece interesante el formato “mesa redonda”? 
Quizás el formato podría ser, mostrar en 15 min los fragmentos más significativos tanto del Gist como de la charla de Robert ( yo me encargaría de añadir subtítulos ) y a partir de ahí ver lo que surge.

Saludos

**Comment by skozz** [comment]
Me mola mucho tu propuesta David. 

Es más hace poco en un briefing en Barcelona comentamos varios desarrolladores ese punto. Por ejemplo a día de hoy he desestimado gran parte del patrón MVC o cambiado la forma de estructurar el código pensando más en contexto que en funcionalidad. 

Hace poco preparé para nuestros desarrollos con React un compilador que sigue convenciones (propias), siguiendo la filosofía de Rails desde sus inicios, así que organizando por contexto y compilando por convención. 

David, has tocado un tema que me gusta mucho.

![giphy](https://cloud.githubusercontent.com/assets/1021463/7491121/94d0188a-f3e6-11e4-840a-a99b19ceed39.gif)

**Comment by DavidBM** [comment]
Yo me apunto a la discusión, aunque seré más oyente que otra cosa.
Además, el formato introducción + mesa redonda me parece muy interesante y creo que puede enriquecer mucho a la comunidad.

**Comment by alferpal** [comment]
+1

**Comment by fjaguero** [comment]
¿Cómo quedamos con esto? ¿Lo pasamos por la lista para hacerlo a mitad de mes? ¿Cómo lo ven?

**Comment by DavidBM** [comment]
Depende de los espacios. Pero una fecha sobre el día 25 la veo adecuada.
Lo de hacerlo cenando me gusta. Supongo que pizza a raudales y mesa lo más redonda posible.

**Comment by danicatalan** [comment]
JS y pizza? +100000!!

**Comment by jonastg** [comment]
A mi también me mola la idea!! :D

**Comment by Bloodsucker** [comment]
Yo me apunto a la cena y a lo que haga falta! :) Aunque en mi opinión creo
que sería más interesante que se convirtiera en una mesa redonda y después
cenita :) En una cena en seguida se hacen minigrupos (distancia, amistad,
etc), se cambian de temas y no hay moderación. Pero sólo es mi opinión jeje

2015-06-08 21:27 GMT+02:00 Jonas Talavera notifications@github.com:

> A mi también me mola la idea!! :D
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Valencia-JS/talks/issues/7#issuecomment-110113629.

## 

José Cabo Carsí - josecabocarsi@gmail.com
LinkedIn: https://www.linkedin.com/in/josecabo
Stackoverflow: http://stackoverflow.com/users/1604261/jose-cabo
Github: https://github.com/Bloodsucker
UPV: _Ingeniero Informático Superior_ | _Escuela Técnica Superior de
Ingeniería Informática_ | _Universidad Politécnica de Valencia_ - Spain
LUT - Computer Science master courses | Lappeenranta University of
Technology - Finland

**Comment by josesegarra** [comment]
Yo tambien me apunto. A la cena y a la mesa redonda !!!

**Comment by logongas** [comment]
Yo me apunto.
Y si estáis buscando sitio, lo podríamos hacer en mi instituto en Mislata con ordenadores y pizarra. La única pega es que tiene que acabar a las 8:00, por lo que tendría que empezar pronto.

**Comment by jonastg** [comment]
Creo que José Cabo tiene razón y lo ideal sería hacer primero la mesa redonda y después cena puesto que el ambiente se relajará y nos desviaremos a otros temas.

**Comment by llunaplanet** [comment]
Buenas, genial pues, @fjaguero vayamos proponiendo fechas!

Sobre el tema del sitio, lo de los ordenadores da igual, pero hace falta un proyector para poner cachitos de la charla de Rob.

Sugerencias?

Salut

**Comment by logongas** [comment]
@llunaplanet En el instituto proyector también hay.

**Comment by lhoyos** [comment]
En Finametrix podríamos alojar la mesa redonda, andamos algo justos de espacio pero podríamos reorganizar para tener capacidad para unas 20 personas. Tenemos proyector

**Comment by antoniobusrod** [comment]
+1

**Comment by fidelab** [comment]
I'm in.

**Comment by llunaplanet** [comment]
Ok, propongo como fecha el 23 de Junio, el lugar pues dependerá un poco de cuantos seamos, no?

Saludos!

**Comment by fjaguero** [comment]
En ese caso, ¿cuanta gente que puede para el 23 también podría para el 24? Justo el 23 estoy fuera de Valencia :(

**Comment by llunaplanet** [comment]
23-24 Lo mismo da :) He puesto 23 por que lo habitual era los Martes, pero
me es igual

Saludos!

2015-06-11 11:00 GMT+02:00 Fernando Agüero notifications@github.com:

**Comment by skozz** [comment]
En cualquiera de los casos sería sobre las 20:00 no? Por organizarme yo y confirmar si puedo, que siempre tengo conflicto con los horarios del evento xD

**Comment by lhoyos** [comment]
Yo puedo martes, a las 20:00 está bien

**Comment by alferpal** [comment]
Yo veo 24 mejor. En cualquier caso, Count me in

**Comment by jonastg** [comment]
22 y 23 coincide con la mediterraneajs en Barcelona, si lo hacemos el 24 y alguien va, nos puede hacer un resumen de lo más interesante :)

**Comment by antoniobusrod** [comment]
+1 jonastg solo si alguien va a mediterraneajs

**Comment by Bloodsucker** [comment]
Otro para el día 24! :D

2015-06-11 11:13 GMT+02:00 Antonio Bustos notifications@github.com:

> +1 jonastg solo si alguien va a mediterraneajs
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Valencia-JS/talks/issues/7#issuecomment-111053915.

## 

José Cabo Carsí - josecabocarsi@gmail.com
LinkedIn: https://www.linkedin.com/in/josecabo
Stackoverflow: http://stackoverflow.com/users/1604261/jose-cabo
Github: https://github.com/Bloodsucker
UPV: _Ingeniero Informático Superior_ | _Escuela Técnica Superior de
Ingeniería Informática_ | _Universidad Politécnica de Valencia_ - Spain
LUT - Computer Science master courses | Lappeenranta University of
Technology - Finland

**Comment by DavidBM** [comment]
A mi me viene mejor el día 24. 

¿Qué lugares hay como opción?

**Comment by danicatalan** [comment]
Otro mas que se apuntaria el 24 ;)

**Comment by logongas** [comment]
Yo prefiero el 23 pero el 24 intentaría ir.

**Comment by fidelab** [comment]
El 24 no creo que pueda ir, el 23 sí :)

**Comment by llunaplanet** [comment]
Ya me he perdido :) ... aquí un doodle para ver opciones de fechas, please
rellenarlo con vuestras preferencias, he añadido el Día 30

Saludos!

http://doodle.com/rk3zy92u6z7zdsz9

2015-06-12 12:15 GMT+02:00 fidelab notifications@github.com:

**Comment by fjaguero** [comment]
Yo voy al MediterraneaJS, por eso lo decía.

**Comment by fjaguero** [comment]
¿Cómo quedó esto al final? ¿Martes 30 por lo que veo no?

**Comment by Bloodsucker** [comment]
O 24 :-)

2015-06-20 15:01 GMT+02:00 Fernando Agüero notifications@github.com:

> ¿Cómo quedó esto al final? ¿Martes 30 por lo que veo no?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Valencia-JS/talks/issues/7#issuecomment-113762115.

## 

José Cabo Carsí - josecabocarsi@gmail.com
LinkedIn: https://www.linkedin.com/in/josecabo
Stackoverflow: http://stackoverflow.com/users/1604261/jose-cabo
Github: https://github.com/Bloodsucker
UPV: _Ingeniero Informático Superior_ | _Escuela Técnica Superior de
Ingeniería Informática_ | _Universidad Politécnica de Valencia_ - Spain
LUT - Computer Science master courses | Lappeenranta University of
Technology - Finland

**Comment by llunaplanet** [comment]
Pues al parecer hay empate, se puede hacer el 24 pero igual es un poco
precipitado para el tema sitio y demás, no? Fernando?

Saludos!

2015-06-20 16:18 GMT+02:00 José Cabo notifications@github.com:

**Comment by danicatalan** [comment]
Para el 24 me parece ya muy precipitado (y eso que a mi me venia mejor).

Si se hace este mes, deberia ser el 30.

**Comment by logongas** [comment]
El 30 es mejor dia ya que asi Fernando nos puede contar algo del MediterraneaJS

**Comment by fjaguero** [comment]
@logongas @llunaplanet Al final no voy a ir al Mediterranea, que toca priorizar. Por el tema sitio, tengo que confirmar con geekshub en caso de hacerlo el 30.

**Comment by fjaguero** [comment]
Ya me confirman desde Geekshubs para el día 30. ¿Misma hora que siempre? ;)

**Comment by llunaplanet** [comment]
Perfecto! Sip, misma hora

**Comment by danicatalan** [comment]
Apuntado! Alli nos vemos.

**Comment by DavidBM** [comment]
¡Perfecto!

**Comment by antoniobusrod** [comment]
:+1:

**Comment by antoniobusrod** [comment]
¿Vais a crear un evento desde el grupo de Meetup o usamos este hilo para notificar asistencia?

**Comment by fjaguero** [comment]
Lo estamos gestionando desde meetup. http://www.meetup.com/es/ValenciaJS/events/223474228/

**Comment by fjaguero** [comment]
En Geekshubs nos permiten hacer streaming del evento, pero no sé si será necesario porque no aportará mucho en mi opinión (habrá que ir pasando el micrófono, etc) ¿Cómo lo ven?

**Comment by llunaplanet** [comment]
Ufff no aporta, a no ser que hubiera un micro para cada uno :), y tener que
esperar a intervenir hasta que llegue el micro, no lo veo :)

**Comment by antoniobusrod** [comment]
Gracias Fernando, recibí la notificación via Meetup.

:+1: por descartar micro
