### ISSUE TITLE
Modularizando JavaScript en el navegador

### ISSUE THREAD

**Issue by DavidBM** [Valencia-JS/talks#8]
# Título

Modularizando JavaScript en el navegador
# Formato

Charla
## Nivel

Medio
# Descripción

> Programas JavaScript. Sabes que el frontend mola mucho pero no puedes dejar de mirar a tu compañero backend, componiéndolo todo tan ordenado, tan limpio y con un archivo para cada clase. 
> 
> Sabes que, cuando funciona tu te llevas las felicitaciones, cuando falla la bronca se la lleva el backend, pero aun así, desde la oscuridad, quieres poder componer código de la misma forma que el.

En esta charla daremos un repaso a lo que significa tener el navegador web como entorno de ejecución y como solventar sus problemas, al mismo tiempo que mejoramos nuestra velocidad de programación, nuestra calidad de código y de vida y gastamos menos tiempo programando y más sonriendo por que alguien ya ha hecho nuestro trabajo.

Hablaremos de como modularizar Javascript, preprocesado y como usar paquetes de nodejs en el navegador web con browserify. También mencionaremos alternativas y la filosofía de cada una.
# Indice de la charla (aprox)
- El navegador como entorno
- Los frameworks al rescate
- El copy-paste tiene que morir
- La era de los buscadores de paquetes
- Pequeñito pero matón. Componiendo módulos.
- Building
- Transforms and Transpilers
- ¿Que opciones tenemos?
# Quien soy?

Empecé a programar en C, luego C++ y acabé en JavaScript. Ahora estoy mirando de iniciarme en programación funcional con haskell. Soy lead frontend en Arpic Games, donde estamos haciendo [Starriser](http://www.starriser.com/), un juego de navegador web MMO de estrategia espacial en webgl.

**Comment by fjaguero** [comment]
Genial, ¿entonces en principio para la siguiente de Junio? Quiero ver ese evangelism de Browserify.

**Comment by DavidBM** [comment]
Ok, me la prepararé durante esta semana y la siguiente. Así tengo tiempo de iterarla. 
Si alguien quiere que comente algún tema en la charla, que lo proponga :)

**Comment by DavidBM** [comment]
Dejo el link a las diapositivas y cierro la issue.

https://docs.google.com/presentation/d/1_rv0xQPsY3Pq2tUEChyzrRcXCtdfbTb0o3P4ZhoTfSY/edit?usp=sharing
