### ISSUE TITLE
TDD for kids (with Google Spreadsheets and JS of course)

### ISSUE THREAD

**Issue by wolframkriesing** [Valencia-JS/talks#9]
Most probably I might only be there for the July meetup, since I am not living in VLC.

**Comment by llunaplanet** [comment]
Hi Wolfram, welcome, the subject seems very interesting, can you describe it a little bit? is it a Talk or a Workshop?

Cheers

**Comment by wolframkriesing** [comment]
Hi,

its acutally just a talk, but would be a lot of fun doing it as a
mini-workshop (or a real one which would be too much for one night i guess)
The abstract I normally use is the following:

In order to get hooked by TDD it sometimes seems too much effort to setup
things, but that should not be the barrier. Along came Google Spreadsheets
and I had a no-setup environment, at least for doing katas and showing of
the magic of being rewarded with a red box switching to green once I
implemented the right thing. I will tell you the story of how I tried to
make TDD as simple as possible and how I ended up with Google Spreadsheets
and also how this inspired me to build tddbin.com for use at our
JSCodeRetreats.
I believe it's the red-green cycle that got them hooked. I did it with
students and also kids even a manager asked me "why does not everyone
program like that?".

## 

Kind regards / Saludos / Mit freundlichen Grüßen
Wolfram Kriesing, uxebu Co-Founder

kriesing@uxebu.com, mobile: +49 174 300 4595

ECMAScript6+React.js workshop http://meetu.ps/2Jds4D
Learn ES6, one kata a day http://es6katas.org

uxebu GmbH
Fraunhofer Straße 31e
86167 Augsburg

Amtsgericht Augsburg, Handelsregister HRB 28613
Directors: W. Kriesing, T. v. Klipstein

**Comment by fjaguero** [comment]
Hi @wolframkriesing, I am trying to confirm the next meetup. We also have a React talk so we need to confirm the dates, how does July 28 sounds for you?

**Comment by wolframkriesing** [comment]
sounds pretty awesome. But dont change the date just for me!
I will join if it works out and I will do my best to make it work out :)

## 

Kind regards / Saludos / Mit freundlichen Grüßen
Wolfram Kriesing, uxebu Co-Founder

kriesing@uxebu.com, mobile: +49 174 300 4595

ECMAScript6+React.js workshop http://meetu.ps/2Jds4D
Learn ES6, one kata a day http://es6katas.org

uxebu GmbH
Fraunhofer Straße 31e
86167 Augsburg

Amtsgericht Augsburg, Handelsregister HRB 28613
Directors: W. Kriesing, T. v. Klipstein

**Comment by fjaguero** [comment]
Ok, I will set the date because it's fine for @skozz too (he will do the other talk) and just ping whenever you know if it's going to be possible. Thanks!

**Comment by wolframkriesing** [comment]
28th is definitely possible
Am 02.07.2015 12:50 schrieb "Fernando Agüero" notifications@github.com:

**Comment by fjaguero** [comment]
@wolframkriesing @skozz I will be creating the meetup event for the 28th then, just waiting for the space confirmation. It will be in Las Naves http://collaborativespace.lasnaves.com/. Waiting for 40-50 persons.

**Comment by fjaguero** [comment]
@wolframkriesing About the talks, I think that his one is more interesting in terms of general knowledge... I'm more curious abot this one. What about doing an intro to es6katas and doing this one?

**Comment by wolframkriesing** [comment]
yo hago todo que pensais que va bien para vuestro publico.
tambien mesclaria español con mi espanõ-ingles :)
Gracias para organicarlo todo, I am excited to join you!

## 

Kind regards / Saludos / Mit freundlichen Grüßen
Wolfram Kriesing, uxebu Co-Founder

kriesing@uxebu.com, mobile: +49 174 300 4595

ECMAScript6+React.js workshop http://meetu.ps/2Jds4D
Learn ES6, one kata a day http://es6katas.org

uxebu GmbH
Fraunhofer Straße 31e
86167 Augsburg

Amtsgericht Augsburg, Handelsregister HRB 28613
Directors: W. Kriesing, T. v. Klipstein
